import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "logout": "Log out",
          "welcome": "Welcome",
          "income": "Income",
          "expenses": "Expenses",
          "balance": "Balance",
          "expense": "Expense",
          "food": "Food",
          "bills": "Bills",
          "transportation": "Transportation",
          "home": "Home",
          "entertainment": "Entertainment",
          "shopping": "Shopping",
          "clothing": "Clothing",
          "insurance": "Insurance",
          "telephone": "Telephone",
          "health": "Health",
          "sport": "Sport",
          "beauty": "Beauty",
          "education": "Education",
          "gift": "Gift",
          "pet": "Pets",
          "salary": "Salary",
          "awards": "Awards",
          "grants": "Grants",
          "rental": "Rental",
          "investment": "Investment",
          "lottery": "Lottery",
          "statistics": "Statistics",
          "wanna_leave?": "Do you wanna leave ?",
          "yes": "Yes",
          "no": "No",
          "change_language": "Change language",
          "No_Data_for_this_month": "No Data for this month",
          "add": "Add",
          "details": "Details",
          "delete": "Delete",
          "delete_confirm": "Are you sure do you want to delete this transaction ?",
          "cancel": "Cancel",
          "label": "Label",
          "category": "Category",
          "amount": "Amount",
          "date": "Date",
          "label": "Label",
          "edit": "Edit",
          "enter_label": "Enter a memo for your transcation",
          "enter_amount": "Enter a the amount for the transcation",
          "select_date": "SELECT DATE",
          "required_field": "Required field",
          "no_tr": "No transactions\nTap + to add one.",
          "numeric_field": "Value has to be numeric",
        },
        'fr': {
          "no_tr": "Aucune transaction\n Appuyez sur + pour en ajouter une.",
          "required_field": "Champ obligatoire",
          "delete_confirm": "Êtes-vous sûr de vouloir supprimer cette transaction ?",
          "select_date": "Selectionner une date",
          "enter_amount": "Saisissez une monatnt pour votre transaction",
          "enter_label": "Saisissez une libellé pour votre transaction",
          "edit": "Modifier",
          "logout": "Déconnecter",
          "welcome": "Bienvenue",
          "income": "Revenu",
          "expenses": "Charges",
          "balance": "Solde",
          "expense": "Charge",
          "food": "Nourriture",
          "bills": "Factures",
          "transportation": "Transport",
          "home": "Maison",
          "entertainment": "Divertissement",
          "clothing": "Vêtements",
          "insurance": "Assurance",
          "telephone": "Téléphone",
          "health": "Santé",
          "sport": "Sport",
          "beauty": "Beauté",
          "gift": "Cadeau",
          "pet": "Animeaux",
          "salary": "Salaire",
          "awards": "Prix",
          "grants": "Subventions",
          "rental": "Location",
          "lottery": "Lot",
          "statistics": "Statistiques",
          "wanna_leave?": "Voulez-vous partir ?",
          "yes": "Oui",
          "no": "Non",
          "change_language": "Changer la langue",
          "No_Data_for_this_month": "Pas de données pour ce mois",
          "add": "Ajouter",
          "details": "Details",
          "delete": "Supprimer",
          "cancel": "Annuler",
          "label": "Libellé",
          "category": "Catégorie",
          "amount": "Montant",
          "date": "Date",
          "numeric_field": "Valeur doit étre numérique",
        },
      };
}
